---
title: "Untitled"
author: "Oliver Lang"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(here,tidyverse,estimatr,fixest,broom,tidyr,haven,modelsummary)
```

## Scheve and Stasavage Replication

```{r replication data}
rel_dta <- read_dta(here("replication","scheve-stasavage_2006","wvalaggSSrep.dta"))

######## table 1 #########

# g import dv
rel_t1_mod1 <- feols(ssw ~ godimp + gini_8090 + trade + prop65 + maj +
                    cath + buddh,
                  data = rel_dta[rel_dta$oecd==1,])
# relig. import dv
rel_t1_mod2 <- feols(ssw ~ relpractice + gini_8090 + trade + prop65 + maj
                  + cath + buddh,
                  data = rel_dta[rel_dta$oecd==1,])

######## table 2 #########
issp_dta <- 
  read_dta(here("replication","scheve-stasavage_2006","isspindSSrep.dta"))[issp_dta$hiincoecd2==1,]


# model formulas
control_vars_1 <- c("female", "educyrs2", "age", "famquart", "unemployed", "union", "cath", "protes",
                  str_subset(colnames(issp_dta),"coecdA")) # country fixed effects

control_vars_2 <- c("female", "educyrs2", "age", "famquart", "unemployed", "union", "cath", "protes","partylr",
                  str_subset(colnames(issp_dta),"coecdA")) 

rel_t2_form1 <- reformulate(c("respattnd",control_vars_1),
                            response = "spend3")

rel_t2_form2 <- reformulate(c("respattnd",control_vars_2), 
                            response = "spend3")
# run models
rel_t2_mod1 <- feols(rel_t2_form1,
                     data = issp_dta, # only oecd
                     weights = issp_dta$weightfctr)
model_obj_lm <- lm(rel_t2_form1,
                     data = issp_dta, # only oecd
                     weights = issp_dta$weightfctr)


rel_t2_mod2 <- feols(rel_t2_form2,
                     data = issp_dta, # only oecd
                     weights = issp_dta$weightfctr)

# cluster SEs at country level
rel_t2_mod1_se <- summary(rel_t2_mod1, cluster = "cntryna2")
rel_t2_mod2_se <- summary(rel_t2_mod2, cluster = "cntryna2")

rel_t2_mods <- list(rel_t2_mod1_se, rel_t2_mod2_se)

modelplot(
  rel_t2_mods,
  coef_map = c("respattnd" = "Religious Attendance")
) +
  labs(caption = 'Dependent variable: Support for social spending')

```

### Regression Weights

```{r}
# observations not removed in regression
issp_used_1 <- issp_dta[-rel_t2_mod1$obsRemoved,]
issp_used_2 <- issp_dta[-rel_t2_mod2$obsRemoved,]

rel_treat_on_cont_form1 <- reformulate(control_vars_1, response = "respattnd")
rel_treat_on_cont_form2 <- reformulate(control_vars_2, response = "respattnd")

# get residuals from regression of treatment on controls
rel_t2_dtilde_1 <- feols(rel_treat_on_cont_form1, data = issp_used_1)$residuals
rel_t2_dtilde_2 <- feols(rel_treat_on_cont_form2, data = issp_used_2)$residuals

rel_t2_weights_1 <- rel_t2_dtilde_1^2
rel_t2_weights_2 <- rel_t2_dtilde_2^2
```

```{r}
# only supports formulas in which fixed effects are manually entered as controls

calculate_w <- function(model_object, treatment, data) { 
  
  surv_weights <- model_object$weights
  
  if (class(model_object)=="fixest") {
    # only select observations that weren't automatically dropped during regression
    obs <- data[-model_object$obsRemoved,]
    # model regressing treatment on all covs
    d_tilde_form <- reformulate( 
      termlabels = all.vars(model_object$fml)[-c(1,which(all.vars(model_object$fml)==treatment))],
      response = treatment
    )
    # squared residuals from regression
    d_tilde <- lm(d_tilde_form, data = obs)$residuals^2
  }
  
  if (class(model_object)=="lm") {
    # only select observations that weren't automatically dropped during regression
    obs <- model_object$model
    
    d_tilde_form <- reformulate(
      termlabels = all.vars(model_object$terms[[3]])[-which(all.vars(model_object$terms[[3]])==treatment)],
      response = treatment
    )
    
    d_tilde <- lm(d_tilde_form, data = obs)$residuals^2
  }
  
  out <- list("d_tilde" = d_tilde, "data" = obs, "treatment" = treatment)
  
  return(out)
}

weights <- calculate_w(model_object, data = issp_dta, treatment = "respattnd")
```

### Visualize

The next step is to visualize the distribution of weights by different covariate values. This has several goals: first, it 

```{r}
plot_weights <- function(weights,
                         type,
                         var,
                         ordinal = FALSE,
                         probs = seq(.1,1,length.out=10)) { 
  
  if (lapply(weights$data, class)[which(colnames(weights$data) == var)] == "numeric") { # if variable is numeric
    
    var_vals <- weights$data[,which(colnames(weights$data) == var)]
    
    var_quantiles <- quantile(var_vals, probs = probs)
    
    # order weight vector by value that variable takes
    # smallest to largest
    ascending_var_index <- sort(var_vals, index.return=TRUE)$ix
    ascending_weights <- weights$d_tilde[ascending_var_index]
    
    q <- seq(.1,1, length.out=10)
    
    unweighted_qtiles <- c()
    weighted_qtiles <- c()
    
    for (j in seq_along(q)) {
      for (i in seq_along(ascending_weights)) {
        if (sum(ascending_weights[1]:ascending_weights[i]) >= q[j]){
          unweighted_qtiles[j] <- ascending_var_index[i]
          break
      }
      
      }
      
    }
    
    
    
    
    
    x <- funciton(x, y, t = 0.5) {
      ord <- order(y/x)
      z <- (y/x)[ord]
      wabs <- abs(x[ord])
      k <- sum(cumsum(wabs) < ((t - 0.5) * sum(x) + 0.5 * sum(wabs)))
      z[k + 1]
    }
    
    
    
    
    
    
    
    
    plot()
    plot()
    
    
    
    weights$d_tilde[]
    
  }
  
  
  





by_country_weights_1 <- tapply(rel_t2_weights_1, issp_used_1$cntryna2, mean)
by_country_weights_2 <- tapply(rel_t2_weights_2, issp_used_2$cntryna2, mean)




```



